name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: '[pushdist]: Pushing new dist files'
      CI_COMMIT_AUTHOR: '[pushdist]'
    steps:
    - uses: actions/checkout@v3

    # Build steps
    - uses: actions/setup-node@v3
      with:
        node-version: '18.12.1' 
    - name: Node Install
      run: npm ci
    - name: Node Dist
      run: npm run dist

    # Commit and push all changed files.
    - name: GIT Commit Build
      # Only run on main branch push (e.g. after pull request merge).
      if: github.event_name == 'push'
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "apenaspara1998@gmail.com"
        git add build/
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
